# Authentication mechanisms
SYNAPSE_AUTH_MECHANISM_SQL_PASSWORD = "SqlPassword"
SYNAPSE_AUTH_MECHANISM_AD_PASSWORD = "ActiveDirectoryPassword"
SYNAPSE_AUTH_MECHANISM_AD_MSI = "ActiveDirectoryMsi"
SYNAPSE_AUTH_MECHANISM_AD_SERVICE_PRINCIPAL = "ActiveDirectoryServicePrincipal"
SYNAPSE_VALID_AUTH_MECHANISMS = [
    SYNAPSE_AUTH_MECHANISM_AD_PASSWORD,
    SYNAPSE_AUTH_MECHANISM_AD_MSI,
    SYNAPSE_AUTH_MECHANISM_AD_SERVICE_PRINCIPAL,
    SYNAPSE_AUTH_MECHANISM_SQL_PASSWORD,
]
SYNAPSE_USER_PASS_AUTH_MECHANISMS = [
    SYNAPSE_AUTH_MECHANISM_AD_PASSWORD,
    SYNAPSE_AUTH_MECHANISM_SQL_PASSWORD,
]
