/* Test as many Oracle data types as possible with result cache */
select /*+ GLUENT_FORCE_RESULT_CACHE */
  COL_BINARY_DOUBLE
-- Add back in after GOE-1718
--, COL_BINARY_FLOAT
, COL_BLOB
, COL_CHAR
, COL_CLOB
, COL_DATE
, COL_DATE_DATE
, COL_DATE_TIMESTAMP_TZ
, COL_DATE_VARIABLE_STRING
, COL_FLOAT
, COL_FLOAT_DOUBLE
, COL_INTERVAL_DAY_TO_SECOND
-- INTERVAL_YM not supported by cx_Oracle
--, COL_INTERVAL_YEAR_TO_MONTH
, COL_NCHAR
, COL_NCLOB
, COL_NUMBER
, COL_NUMBER_18
, COL_NUMBER_2
-- These are not guaranteed across all backends
--, COL_NUMBER_38
--, COL_NUMBER_38_18
, COL_NUMBER_4
, COL_NUMBER_9
, COL_NUMBER_DOUBLE
, COL_NUMBER_INTEGER_1
, COL_NUMBER_INTEGER_2
, COL_NUMBER_INTEGER_38
, COL_NUMBER_INTEGER_4
, COL_NUMBER_INTEGER_8
, COL_NVARCHAR2
, COL_RAW
, COL_TIMESTAMP
, COL_TIMESTAMP_DATE
, COL_TIMESTAMP_TIMESTAMP_TZ
, COL_TIMESTAMP_VARIABLE_STRING
, COL_TIMESTAMP_WITH_TIME_ZONE
, COL_VARCHAR2
from gl_type_mapping
