define _app_schema = &1

alter session set current_schema = &_app_schema;

CREATE TABLE "SALES_R15"
(	"ID" NUMBER NOT NULL ENABLE,
    "PROD_ID" NUMBER NOT NULL ENABLE,
	"CUST_ID" NUMBER NOT NULL ENABLE,
	"TIME_ID" DATE NOT NULL ENABLE,
	"CHANNEL_ID" NUMBER NOT NULL ENABLE,
	"PROMO_ID" NUMBER NOT NULL ENABLE,
	"QUANTITY_SOLD" NUMBER(10,2) NOT NULL ENABLE,
	"AMOUNT_SOLD" NUMBER(10,2) NOT NULL ENABLE,
	 CONSTRAINT "SALES_R15_PK" PRIMARY KEY ("TIME_ID", "ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
LOCAL TABLESPACE "USERS"  ENABLE NOVALIDATE,
CONSTRAINT "SALES_R15_CUSTOMER_FK" FOREIGN KEY ("CUST_ID")
	  REFERENCES "CUSTOMERS" ("CUST_ID") ENABLE NOVALIDATE,
	 CONSTRAINT "SALES_R15_PRODUCT_FK" FOREIGN KEY ("PROD_ID")
	  REFERENCES "PRODUCTS" ("PROD_ID") ENABLE NOVALIDATE,
	 CONSTRAINT "SALES_R15_TIME_FK" FOREIGN KEY ("TIME_ID")
	  REFERENCES "TIMES" ("TIME_ID") ENABLE NOVALIDATE,
	 CONSTRAINT "SALES_R15_CHANNEL_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "CHANNELS" ("CHANNEL_ID") ENABLE NOVALIDATE,
	 CONSTRAINT "SALES_R15_PROMO_FK" FOREIGN KEY ("PROMO_ID")
	  REFERENCES "PROMOTIONS" ("PROMO_ID") ENABLE NOVALIDATE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
STORAGE(
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS"
PARTITION BY RANGE ("TIME_ID")
INTERVAL (NUMTODSINTERVAL(1,'day'))
(PARTITION "SALES_R15_20150621"  VALUES LESS THAN (TO_DATE(' 2015-06-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS");

CREATE BITMAP INDEX "SALES_R15_CHANNEL_BIX" ON "SALES_R15" ("CHANNEL_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
(PARTITION "SALES_R15_20150621"
PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" );

CREATE BITMAP INDEX "SALES_R15_CUST_BIX" ON "SALES_R15" ("CUST_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
(PARTITION "SALES_R15_20150621"
PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" );

CREATE BITMAP INDEX "SALES_R15_PROD_BIX" ON "SALES_R15" ("PROD_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
(PARTITION "SALES_R15_20150621"
PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" );

CREATE BITMAP INDEX "SALES_R15_PROMO_BIX" ON "SALES_R15" ("PROMO_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
(PARTITION "SALES_R15_20150621"
PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" );

CREATE BITMAP INDEX "SALES_R15_TIME_BIX" ON "SALES_R15" ("TIME_ID")
PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
(PARTITION "SALES_R15_20150621"
PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" );

INSERT INTO "SALES_R15" SELECT ROWNUM, SALES.* FROM "SALES" WHERE TIME_ID >=  TO_DATE(' 2015-06-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN') ORDER BY TIME_ID;

COMMIT;

