/*
# Copyright 2016 The GOE Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/

set termout off feedback off serveroutput on
spool sql/create_offload_repo.tmp replace
begin
    dbms_output.put_line(q'{-- Script generated by create_offload_repo.sql}');
    dbms_output.put_line(q'{-- Copyright ' || to_char(sysdate, 'YYYY') || ' The GOE Authors. All rights reserved.}');
    dbms_output.put_line(q'{--}');
    if '&goe_repo_install' = 'Y' then
        dbms_output.put_line('@@install_offload_repo.sql');
    elsif '&goe_repo_upgrade' = 'Y' then
        dbms_output.put_line('@@upgrade_offload_repo.sql');
    end if;
end;
/
spool off
set termout on feedback on serveroutput off

@@create_offload_repo.tmp
