-- install_offload_code.sql
--
-- LICENSE_TEXT
--
--prompt Creating contexts...
--@@create_offload_context.sql
prompt Creating types...
@@create_offload_types.sql
prompt Creating views...
@@create_offload_views.sql
prompt Creating packages...
@@create_offload_packages.sql
prompt Creating synonyms...
@@create_offload_synonyms.sql
prompt Creating grants...
@@create_offload_grants.sql
