-- repo_env.sql
--
-- LICENSE_TEXT
--
whenever sqlerror exit failure
whenever oserror exit failure

undefine goe_repo_install
undefine goe_repo_upgrade

col goe_repo_upgrade new_value goe_repo_upgrade
col goe_repo_install new_value goe_repo_install
select decode(count(*), 0, 'Y', 'N') as goe_repo_install
     , decode(count(*), 0, 'N', 'Y') as goe_repo_upgrade
  from dba_tables
 where owner = '&goe_db_repo_user';

spool sql/repo_env.tmp replace
set serveroutput on feedback off
begin
    dbms_output.put_line(q'{-- Script generated by repo_env.sql}');
    dbms_output.put_line(q'{-- LICENSE_TEXT}');
    dbms_output.put_line(q'{--}');
    if '&goe_repo_install' = 'Y' then
        dbms_output.put_line('@@install_repo_env.sql');
    else
        dbms_output.put_line('@@upgrade_repo_env.sql');
    end if;
end;
/
spool off

@@repo_env.tmp
