-- uninstall_offload_repo.sql
--
-- LICENSE_TEXT
--

set termout off feedback off serveroutput on
spool sql/uninstall_offload_repo.tmp replace
begin
    dbms_output.put_line(q'{-- Script generated by uninstall_offload_repo.sql}');
    dbms_output.put_line(q'{-- LICENSE_TEXT}');
    dbms_output.put_line(q'{--}');
    if '&gluent_repo_installed' = 'Y' and '&gluent_repo_uninstall' = 'Y' then
        dbms_output.put_line(q'{set termout on feedback on}');
        dbms_output.put_line(q'{prompt Uninstalling Gluent Metadata Repository...}');
        dbms_output.put_line(q'{drop user &gluent_db_repo_user cascade;}');
        dbms_output.put_line(q'{drop role GLUENT_OFFLOAD_REPO_ROLE;}');
    end if;
end;
/
spool off

@@uninstall_offload_repo.tmp
