-- uninstall_env.sql
--
-- LICENSE_TEXT
--
whenever sqlerror exit failure
whenever oserror exit failure
undefine gluent_db_user_prefix
undefine gluent_db_adm_user
undefine gluent_db_app_user
undefine gluent_db_repo_user
undefine gluent_repo_installed
undefine gluent_repo_uninstall

set termout off
col gluent_db_user_prefix new_value gluent_db_user_prefix
select substr(owner,1,length(owner) - 4) gluent_db_user_prefix
  from dba_objects
 where object_type = 'PACKAGE'
   and object_name = 'OFFLOAD'
   and substr(owner,-4) = '_ADM';

define gluent_db_adm_user = &gluent_db_user_prefix._ADM
define gluent_db_app_user = &gluent_db_user_prefix._APP
define gluent_db_repo_user = &gluent_db_user_prefix._REPO

col gluent_repo_installed new_value gluent_repo_installed
select nvl2(max(username), 'Y', 'N') as gluent_repo_installed
from   dba_users
where  username = '&gluent_db_repo_user';

set serveroutput on feedback off lines 200
spool sql/uninstall_env.tmp replace
begin
    dbms_output.put_line(q'{-- Script generated by uninstall_env.sql}');
    dbms_output.put_line(q'{-- LICENSE_TEXT}');
    dbms_output.put_line(q'{--}');
    if '&gluent_repo_installed' = 'Y' then
        dbms_output.put_line(q'{set termout on}');
        dbms_output.put_line(q'{ACCEPT gluent_repo_uninstall PROMPT 'Uninstall Gluent Metadata Repository? [N]: '}');
    else
        dbms_output.put_line(q'{define gluent_repo_uninstall = "N"}');
    end if;
end;
/
spool off

@@uninstall_env.tmp

set termout off serveroutput off feedback on
col gluent_repo_uninstall new_value gluent_repo_uninstall
select upper(coalesce('&gluent_repo_uninstall', 'N')) as gluent_repo_uninstall
from   dual;

@@verify_uninstall.sql
