#! /bin/bash

# Display Gluent environment variables set by offload.env
#
# Usage: display_gluent_env [<env file>]
#
# LICENSE_TEXT

function display_var() {
    name=$1

    echo "${name} = ${!name:=<unset>}"
}

offload_env_file=$1
[[ -z "${offload_env_file}" ]] && offload_env_file="${OFFLOAD_CONF}/offload.env"
[[ "/" == "${offload_env_file}" || ! -f "${offload_env_file}" ]] && echo "Unable to locate offload.env file. Run as: display_gluent_env <path to offload.env>" && exit
echo -e "Reading variable names from file: ${offload_env_file}\n"

echo -e "Settings in current environment:\n"
offload_vars=$(cat ${offload_env_file} | grep -P 'export \w+' | perl -pale 's/^.*(export \w+).*$/$1/' | sed -e 's/export //' | sort | uniq)

for v in ${offload_vars}
do
    display_var $v
done
