ALTER TABLE COSTS ADD CONSTRAINT COSTS_PROMO_FK FOREIGN KEY (PROMO_ID) REFERENCES WITH NO CHECK OPTION PROMOTIONS (PROMO_ID);
ALTER TABLE COSTS ADD CONSTRAINT COSTS_PRODUCT_FK FOREIGN KEY (PROD_ID) REFERENCES WITH NO CHECK OPTION PRODUCTS (PROD_ID);
ALTER TABLE COSTS ADD CONSTRAINT COSTS_TIME_FK FOREIGN KEY (TIME_ID) REFERENCES WITH NO CHECK OPTION TIMES (TIME_ID);
ALTER TABLE COSTS ADD CONSTRAINT COSTS_CHANNEL_FK FOREIGN KEY (CHANNEL_ID) REFERENCES WITH NO CHECK OPTION CHANNELS (CHANNEL_ID);

ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMERS_COUNTRY_FK FOREIGN KEY (COUNTRY_ID) REFERENCES WITH NO CHECK OPTION COUNTRIES (COUNTRY_ID);

ALTER TABLE SALES ADD CONSTRAINT SALES_CUSTOMER_FK FOREIGN KEY (CUST_ID) REFERENCES WITH NO CHECK OPTION CUSTOMERS (CUST_ID);
ALTER TABLE SALES ADD CONSTRAINT SALES_PRODUCT_FK FOREIGN KEY (PROD_ID) REFERENCES WITH NO CHECK OPTION PRODUCTS (PROD_ID);
ALTER TABLE SALES ADD CONSTRAINT SALES_TIME_FK FOREIGN KEY (TIME_ID) REFERENCES WITH NO CHECK OPTION TIMES (TIME_ID);
ALTER TABLE SALES ADD CONSTRAINT SALES_CHANNEL_FK FOREIGN KEY (CHANNEL_ID) REFERENCES WITH NO CHECK OPTION CHANNELS (CHANNEL_ID);
ALTER TABLE SALES ADD CONSTRAINT SALES_PROMO_FK FOREIGN KEY (PROMO_ID) REFERENCES WITH NO CHECK OPTION PROMOTIONS (PROMO_ID);
