gluent_binds = {"large_timed_id_key": 25895910817830972870695834892749504512, "account_number": 1135934024838695}
gluent_pred_push_tokens = [{"token": ".PAYPAL_LTID_TO_INT64", "occurs": true}, {"token": "LARGE_TIMED_ID_KEY", "occurs": true}, {"token": "ACCOUNT_NUMBER", "occurs": 1}]

SELECT /*+ monitor &_pq &_qre &_test_name gluent_query_monitor */ TRANSACTION_FACT_LTID.TRANSACTION_ID AS TRANSACTION_ID
,      TRANSACTION_FACT_LTID.ENCRYPTED_TRANSACTION_ID AS ENCRYPTED_TRANSACTION_ID 
FROM   TRANSACTION_FACT_LTID
WHERE  LARGE_TIMED_ID_KEY = :large_timed_id_key
AND    ACCOUNT_NUMBER = :account_number 
AND    (   (TRANSACTION_TYPE_CODE='U' AND TRANSACTION_SUBTYPE_CODE IN ('L','O') AND DEBIT_CREDIT_CODE='CR') 
        OR (TRANSACTION_TYPE_CODE='U' AND TRANSACTION_SUBTYPE_CODE='X' AND DEBIT_CREDIT_CODE='DR'))
