name: release

on:
  push:
    branches:
      - main

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  package-goe:
    name: Package GOE artefacts required for installation
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all tags
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup SBT
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.10.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install base libraries
        run: pip install --quiet --upgrade pip build setuptools wheel

      - name: Building GOE package
        run: make package

      - name: Move package to `dist/`
        run: |
          mkdir -p dist
          mv goe_*.tar.gz dist/

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/goe_*.tar.gz
          if-no-files-found: error

  publish:
    name: Publish release
    needs:
      - release-please
      - package-goe
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: dist

      - name: Add package to current release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: dist/goe_*.tar.gz

  pypi-publish:
    name: Publish release to PyPI
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --quiet --upgrade pip build setuptools wheel
      - name: Build package
        run: |
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
